Repository metanet-4/backend, pull requests merged in 2025-02, with the labels that each got.

#50 [Feat] MN-29/마이 페이지 구현 완료 및 merge 완료
  metanet4/pom.xml
  metanet4/src/main/java/com/metanet/team4/config/WebConfig.java
  metanet4/src/main/java/com/metanet/team4/movie/MovieController.java
  metanet4/src/main/java/com/metanet/team4/movie/dao/IMovieRepository.java
  metanet4/src/main/java/com/metanet/team4/movie/dao/MovieRepository.java
  metanet4/src/main/java/com/metanet/team4/movie/service/IMovieService.java
  metanet4/src/main/java/com/metanet/team4/movie/service/MovieService.java
  metanet4/src/main/java/com/metanet/team4/mypage/MypageController.java
  metanet4/src/main/java/com/metanet/team4/mypage/dao/IMypageRepository.java
  metanet4/src/main/java/com/metanet/team4/mypage/dao/MypageRepository.java
  metanet4/src/main/java/com/metanet/team4/mypage/model/MypageMember.java
  metanet4/src/main/java/com/metanet/team4/mypage/model/MypageResponse.java
  metanet4/src/main/java/com/metanet/team4/mypage/model/ReserveList.java
  metanet4/src/main/java/com/metanet/team4/mypage/service/IMypageService.java
  metanet4/src/main/java/com/metanet/team4/mypage/service/MypageService.java
Labels: enhancement

#52 [Feat]회원아이디_전화번호_중복체크와_CLOB에서BLOB으로_수정
  metanet4/src/main/java/com/metanet/team4/jwt/JwtUtil.java
  metanet4/src/main/java/com/metanet/team4/member/controller/AdminController.java
  metanet4/src/main/java/com/metanet/team4/member/controller/AuthController.java
  metanet4/src/main/java/com/metanet/team4/member/controller/UserController.java
  metanet4/src/main/java/com/metanet/team4/member/controller/UserPageController.java
  metanet4/src/main/java/com/metanet/team4/member/mapper/MemberMapper.java
  metanet4/src/main/java/com/metanet/team4/member/model/Member.java
  metanet4/src/main/java/com/metanet/team4/member/service/AdminService.java
  metanet4/src/main/java/com/metanet/team4/member/service/MemberService.java
  metanet4/src/main/java/com/metanet/team4/member/service/UserService.java
  metanet4/src/main/resources/mapper/MemberMapper.xml
  metanet4/src/main/resources/templates/signup.html
Labels: enhancement

#53 feat: movie/{movieId} -> movie/detail/{movieId} 수정
  metanet4/src/main/java/com/metanet/team4/movie/MovieController.java
Labels: enhancement

#54 [feat] 예매 결제 api 추가
  metanet4/src/main/java/com/metanet/team4/config/WebConfig.java
  metanet4/src/main/java/com/metanet/team4/payment/controller/PaymentController.java
  metanet4/src/main/java/com/metanet/team4/payment/controller/ReservController.java
  metanet4/src/main/java/com/metanet/team4/payment/dao/IReservatoinRepository.java
  metanet4/src/main/java/com/metanet/team4/payment/model/PaymentRequestDto.java
  metanet4/src/main/java/com/metanet/team4/payment/model/PaymentResponseDto.java
  metanet4/src/main/java/com/metanet/team4/payment/model/ReservationDetailDto.java
  metanet4/src/main/java/com/metanet/team4/payment/service/PaymentService.java
  metanet4/src/main/java/com/metanet/team4/payment/service/ReservService.java
  metanet4/src/main/resources/mapper/reservation/ReservationMapper.xml
Labels: enhancement

#63 MN-42/feat/알림 기능 구현
  metanet4/pom.xml
  metanet4/src/main/java/com/metanet/team4/config/SecurityConfig.java
  metanet4/src/main/java/com/metanet/team4/websocket/CustomWebSocketHandler.java
  metanet4/src/main/java/com/metanet/team4/websocket/NotificationController.java
  metanet4/src/main/java/com/metanet/team4/websocket/WebSocketConfig.java
  metanet4/src/main/java/com/metanet/team4/websocket/WebSocketService.java
Labels: enhancement

#68 Mn 44/feat/이메일 인증기능 추가 jwt관련 코드 수정
  metanet4/pom.xml
  metanet4/src/main/java/com/metanet/team4/config/SecurityConfig.java
  metanet4/src/main/java/com/metanet/team4/jwt/JwtAuthenticationFilter.java
  metanet4/src/main/java/com/metanet/team4/jwt/JwtUtil.java
  metanet4/src/main/java/com/metanet/team4/member/controller/AdminController.java
  metanet4/src/main/java/com/metanet/team4/member/controller/AuthController.java
  metanet4/src/main/java/com/metanet/team4/member/mapper/MemberMapper.java
  metanet4/src/main/java/com/metanet/team4/member/service/AdminService.java
  metanet4/src/main/java/com/metanet/team4/member/service/EmailService.java
  metanet4/src/main/java/com/metanet/team4/member/service/MemberService.java
  metanet4/src/main/java/com/metanet/team4/member/service/RedisService.java
  metanet4/src/main/resources/mapper/MemberMapper.xml
  metanet4/src/main/resources/static/js/refresh.js
  metanet4/src/main/resources/templates/admin-users.html
  metanet4/src/main/resources/templates/signup.html
Labels: enhancement

#69 Mn 41/feat/예매 선택 페이지 로직 구현
  metanet4/src/main/java/com/metanet/team4/ticket/controller/TicketController.java
  metanet4/src/main/java/com/metanet/team4/ticket/dao/ITicketRepository.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/CinemaFindResponseDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/ScreenFindResponseDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/SeatResponseDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/TicketRequestDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/TicketResponseDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/TimeDto.java
  metanet4/src/main/java/com/metanet/team4/ticket/model/Cinema.java
  metanet4/src/main/java/com/metanet/team4/ticket/model/Playing.java
  metanet4/src/main/java/com/metanet/team4/ticket/model/Screen.java
  metanet4/src/main/java/com/metanet/team4/ticket/model/Seat.java
  metanet4/src/main/java/com/metanet/team4/ticket/service/ITicketService.java
  metanet4/src/main/java/com/metanet/team4/ticket/service/TicketService.java
Labels: enhancement

#72 [feat] 결제완료 시 알림 전송
  metanet4/src/main/java/com/metanet/team4/payment/controller/PaymentController.java
Labels: enhancement

#75 [fix] JwtUtil 파일 수정
  metanet4/src/main/java/com/metanet/team4/jwt/JwtUtil.java
Labels: bug

#82 회원정보수정페이지에서_프로필사진인증서_업로드및변경기능추가
  metanet4/src/main/java/com/metanet/team4/member/controller/UserController.java
  metanet4/src/main/java/com/metanet/team4/member/mapper/MemberMapper.java
  metanet4/src/main/java/com/metanet/team4/member/service/UserService.java
  metanet4/src/main/resources/mapper/MemberMapper.xml
  metanet4/src/main/resources/templates/admin-users.html
  metanet4/src/main/resources/templates/profile.html
  metanet4/src/main/resources/templates/updateInfo.html
Labels: enhancement

#90 [refactor] 상영 정보 조회 시 영화 사진도 가져오도록 수정
  metanet4/pom.xml
  metanet4/src/main/java/com/metanet/team4/ticket/dao/ITicketRepository.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/PlayingResponseDto.java
Labels: enhancement

#91 MN-57/feat/예매로직 테스트 코드 작성
  metanet4/src/main/java/com/metanet/team4/config/SecurityConfig.java
  metanet4/src/main/java/com/metanet/team4/jwt/JwtAuthenticationFilter.java
  metanet4/src/main/java/com/metanet/team4/ticket/controller/TicketController.java
  metanet4/src/main/java/com/metanet/team4/ticket/dto/TicketRequestDto.java
  metanet4/src/test/java/com/metanet/team4/ticket/controller/TicketControllerTest.java
Labels: enhancement

#95 [refactor] 예매 상세 조회를 예매 번호를 기준으로 수정
  metanet4/src/main/java/com/metanet/team4/common/TestDataUtils.java
  metanet4/src/main/java/com/metanet/team4/config/SecurityConfig.java
  metanet4/src/main/java/com/metanet/team4/config/WebConfig.java
  metanet4/src/main/java/com/metanet/team4/payment/controller/ReservController.java
  metanet4/src/main/java/com/metanet/team4/payment/dao/IReservatoinRepository.java
  metanet4/src/main/java/com/metanet/team4/payment/service/PaymentService.java
  metanet4/src/main/java/com/metanet/team4/payment/service/ReservService.java
  metanet4/src/main/resources/mapper/ReservationMapper.xml
  metanet4/src/test/java/com/metanet/team4/reservation/controller/ReservControllerTest.java
Labels: enhancement

#100 MN-72/refactor/알림 수정으로 인한 dto 변경
  metanet4/src/main/java/com/metanet/team4/payment/dao/IReservatoinRepository.java
  metanet4/src/main/java/com/metanet/team4/payment/model/PaymentResponseDto.java
  metanet4/src/main/java/com/metanet/team4/payment/service/PaymentService.java
  metanet4/src/main/resources/mapper/ReservationMapper.xml
Labels: enhancement

#101 fix: 웹소켓 메시지 수정
  metanet4/src/main/java/com/metanet/team4/payment/controller/PaymentController.java
Labels: enhancement

#103 프론트동작위한_코드수정
  metanet4/src/main/java/com/metanet/team4/member/controller/AuthController.java
  metanet4/src/main/java/com/metanet/team4/member/controller/UserController.java
  metanet4/src/main/java/com/metanet/team4/member/service/UserService.java
Labels: enhancement

#109 myPage reservationCode 타입 수정
  metanet4/src/main/java/com/metanet/team4/mypage/dao/MypageRepository.java
  metanet4/src/main/java/com/metanet/team4/mypage/model/ReserveList.java
Labels: bug

#113 refactor: 상영 정보를 가져오는 sql문 수정
  metanet4/src/main/java/com/metanet/team4/mypage/model/ReserveList.java
  metanet4/src/main/java/com/metanet/team4/ticket/dao/ITicketRepository.java
Labels: duplicate

#115 MN-82/feat/캐싱 적용
  metanet4/src/main/java/com/metanet/team4/config/RedisConfig.java
  metanet4/src/main/java/com/metanet/team4/movie/service/MovieListService.java
Labels: enhancement

#117 MN-83/feat/좌석 선택 동시성 처리
  metanet4/src/main/java/com/metanet/team4/payment/dao/IReservatoinRepository.java
  metanet4/src/main/java/com/metanet/team4/payment/service/PaymentService.java
  metanet4/src/main/java/com/metanet/team4/payment/service/ReservService.java
  metanet4/src/main/resources/mapper/ReservationMapper.xml
Labels: enhancement

#119 MN-84/feat/분산 락 메커니즘 적용
  metanet4/pom.xml
  metanet4/src/main/java/com/metanet/team4/config/RedissonConfig.java
  metanet4/src/main/java/com/metanet/team4/payment/service/PaymentService.java
Labels: enhancement
